// Mocks generated by Mockito 5.4.4 from annotations
// in alonu_app/test/artisan_remote_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:alonu_app/data/datasources/artisan_remote_data_source.dart'
    as _i3;
import 'package:alonu_app/data/models/artisan_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeArtisanModel_0 extends _i1.SmartFake implements _i2.ArtisanModel {
  _FakeArtisanModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRealisationModel_1 extends _i1.SmartFake
    implements _i2.RealisationModel {
  _FakeRealisationModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ArtisanRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockArtisanRemoteDataSource extends _i1.Mock
    implements _i3.ArtisanRemoteDataSource {
  MockArtisanRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.CategoryModel>> getCategories() => (super.noSuchMethod(
        Invocation.method(
          #getCategories,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.CategoryModel>>.value(<_i2.CategoryModel>[]),
      ) as _i4.Future<List<_i2.CategoryModel>>);

  @override
  _i4.Future<List<_i2.SubCategoryModel>> getSubcategories(String? categoryId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getSubcategories,
          [categoryId],
        ),
        returnValue: _i4.Future<List<_i2.SubCategoryModel>>.value(
            <_i2.SubCategoryModel>[]),
      ) as _i4.Future<List<_i2.SubCategoryModel>>);

  @override
  _i4.Future<List<_i2.ArtisanModel>> getArtisans({
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArtisans,
          [],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.ArtisanModel>>.value(<_i2.ArtisanModel>[]),
      ) as _i4.Future<List<_i2.ArtisanModel>>);

  @override
  _i4.Future<List<_i2.ArtisanModel>> getArtisansByLocation({
    required double? latitude,
    required double? longitude,
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArtisansByLocation,
          [],
          {
            #latitude: latitude,
            #longitude: longitude,
            #page: page,
            #limit: limit,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.ArtisanModel>>.value(<_i2.ArtisanModel>[]),
      ) as _i4.Future<List<_i2.ArtisanModel>>);

  @override
  _i4.Future<_i2.ArtisanModel> getArtisanDetail(String? artisanId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArtisanDetail,
          [artisanId],
        ),
        returnValue: _i4.Future<_i2.ArtisanModel>.value(_FakeArtisanModel_0(
          this,
          Invocation.method(
            #getArtisanDetail,
            [artisanId],
          ),
        )),
      ) as _i4.Future<_i2.ArtisanModel>);

  @override
  _i4.Future<List<dynamic>> getProducts({
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProducts,
          [],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<List<dynamic>> getPublicApprenticeshipAds({String? countryId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPublicApprenticeshipAds,
          [],
          {#countryId: countryId},
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<List<dynamic>> getCarouselAdvertisements({String? countryId}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCarouselAdvertisements,
          [],
          {#countryId: countryId},
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<dynamic> getProductDetail(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProductDetail,
          [productId],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<List<_i2.ArtisanModel>> searchArtisans(String? query) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchArtisans,
          [query],
        ),
        returnValue:
            _i4.Future<List<_i2.ArtisanModel>>.value(<_i2.ArtisanModel>[]),
      ) as _i4.Future<List<_i2.ArtisanModel>>);

  @override
  _i4.Future<List<_i2.ArtisanModel>> filterArtisans({
    String? category,
    String? location,
    double? minRating,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #filterArtisans,
          [],
          {
            #category: category,
            #location: location,
            #minRating: minRating,
          },
        ),
        returnValue:
            _i4.Future<List<_i2.ArtisanModel>>.value(<_i2.ArtisanModel>[]),
      ) as _i4.Future<List<_i2.ArtisanModel>>);

  @override
  _i4.Future<_i2.ArtisanModel> updateArtisan(
    String? artisanId,
    Map<String, dynamic>? updateData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateArtisan,
          [
            artisanId,
            updateData,
          ],
        ),
        returnValue: _i4.Future<_i2.ArtisanModel>.value(_FakeArtisanModel_0(
          this,
          Invocation.method(
            #updateArtisan,
            [
              artisanId,
              updateData,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ArtisanModel>);

  @override
  _i4.Future<List<dynamic>> getStudentsByArtisan(String? artisanId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStudentsByArtisan,
          [artisanId],
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<dynamic> getStudentDetail(String? studentId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getStudentDetail,
          [studentId],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<dynamic> publishProduct(
    String? artisanId,
    Map<String, dynamic>? productData,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #publishProduct,
          [
            artisanId,
            productData,
          ],
        ),
        returnValue: _i4.Future<dynamic>.value(),
      ) as _i4.Future<dynamic>);

  @override
  _i4.Future<List<dynamic>> getArtisanProducts(
    String? artisanId, {
    int? page = 1,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArtisanProducts,
          [artisanId],
          {
            #page: page,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<List<dynamic>> getArtisanOrders({String? status}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getArtisanOrders,
          [],
          {#status: status},
        ),
        returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
      ) as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> updateOrderStatus(
    String? orderId,
    String? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateOrderStatus,
          [
            orderId,
            status,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> markOrderDelivered(String? orderId) =>
      (super.noSuchMethod(
        Invocation.method(
          #markOrderDelivered,
          [orderId],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<_i2.ArtisanModel> updateArtisanLocation(
    String? artisanId,
    double? latitude,
    double? longitude,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateArtisanLocation,
          [
            artisanId,
            latitude,
            longitude,
          ],
        ),
        returnValue: _i4.Future<_i2.ArtisanModel>.value(_FakeArtisanModel_0(
          this,
          Invocation.method(
            #updateArtisanLocation,
            [
              artisanId,
              latitude,
              longitude,
            ],
          ),
        )),
      ) as _i4.Future<_i2.ArtisanModel>);

  @override
  _i4.Future<_i2.ArtisanModel> createArtisan(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #createArtisan,
          [data],
        ),
        returnValue: _i4.Future<_i2.ArtisanModel>.value(_FakeArtisanModel_0(
          this,
          Invocation.method(
            #createArtisan,
            [data],
          ),
        )),
      ) as _i4.Future<_i2.ArtisanModel>);

  @override
  _i4.Future<List<_i2.RealisationModel>> getRealisations(String? artisanId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRealisations,
          [artisanId],
        ),
        returnValue: _i4.Future<List<_i2.RealisationModel>>.value(
            <_i2.RealisationModel>[]),
      ) as _i4.Future<List<_i2.RealisationModel>>);

  @override
  _i4.Future<_i2.RealisationModel> addRealisation(
    String? artisanId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addRealisation,
          [
            artisanId,
            data,
          ],
        ),
        returnValue:
            _i4.Future<_i2.RealisationModel>.value(_FakeRealisationModel_1(
          this,
          Invocation.method(
            #addRealisation,
            [
              artisanId,
              data,
            ],
          ),
        )),
      ) as _i4.Future<_i2.RealisationModel>);

  @override
  _i4.Future<_i2.RealisationModel> updateRealisation(
    String? artisanId,
    String? realisationId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateRealisation,
          [
            artisanId,
            realisationId,
            data,
          ],
        ),
        returnValue:
            _i4.Future<_i2.RealisationModel>.value(_FakeRealisationModel_1(
          this,
          Invocation.method(
            #updateRealisation,
            [
              artisanId,
              realisationId,
              data,
            ],
          ),
        )),
      ) as _i4.Future<_i2.RealisationModel>);

  @override
  _i4.Future<void> deleteRealisation(
    String? artisanId,
    String? realisationId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteRealisation,
          [
            artisanId,
            realisationId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> updateProduct(
    String? productId,
    Map<String, dynamic>? data,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProduct,
          [
            productId,
            data,
          ],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<void> deleteProduct(String? productId) => (super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [productId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<Map<String, dynamic>> toggleProductActive(String? productId) =>
      (super.noSuchMethod(
        Invocation.method(
          #toggleProductActive,
          [productId],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);

  @override
  _i4.Future<Map<String, dynamic>> createAdvertisement(
          Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #createAdvertisement,
          [data],
        ),
        returnValue:
            _i4.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i4.Future<Map<String, dynamic>>);
}
